### ISSUE TITLE
[Other issue]: Unable to compute a StartSet for robot [ros2_tb3_0] using level_name [L1] and location [-1.894945, -0.420001, 0.000001] specified in its RobotState message. This can happen if the level_name in the RobotState message does not match any of the map names in the navigation graph supplied or if the location reported in the RobotState message is far way from the navigation graph.

### ISSUE THREAD

**Issue by PVijayaGanesh** [open-rmf/free_fleet#151]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Hi I am trying the free_fleet simulation for ros2 galactic and continuing the rmf on turtlebot3..

command 1: ros2 launch  ff_examples_ros2 turtlebot3_world_ff.launch.xml
command 2: ros2 launch ff_examples_ros2 turtlebot3_world_ff_server.launch.xml
                     output: [INFO] [1729077279.129561946] [turtlebot3_fleet_server_node]: registered a new robot: [ros2_tb3_0]
                     
Command 3: ros2 launch  barista_rmf_gazebo start_rmf_turtlebotworld.launch.xml

my **rmf_gazebo start_rmf_turtlebotworld.launch.xml**

```
<?xml version='1.0' ?>
<launch>
  <arg name="failover_mode" default="false"/>
  <arg name="use_sim_time" default="true"/>
  <!-- Common launch -->
  <include file="$(find-pkg-share barista_rmf_gazebo)/launch/rmf_t3_world.launch.xml">
    <arg name="use_sim_time" value="$(var use_sim_time)"/>
    <arg name="failover_mode" value="$(var failover_mode)"/>
    <arg name="map_name" value="ff" />
  </include>
</launch>
```

my **rmf_t3_world.launch.xml**

```
<?xml version='1.0' ?>

<launch>
  <arg name="use_sim_time" default="false"/>
  <arg name="failover_mode" default="false"/>
  <arg name="map_name" description="Name of the rmf_demos map to simulate" />

  <!-- Common launch -->
  <include file="$(find-pkg-share rmf_demos)/common.launch.xml">
    <arg name="use_sim_time" value="$(var use_sim_time)"/>
    <arg name="viz_config_file" value ="$(find-pkg-share barista_rmf_gazebo)/rviz_config/$(var map_name).rviz"/>
    <arg name="config_file" value="$(find-pkg-share barista_rmf_gazebo)/rmf_config/$(var map_name).building.yaml"/>
    <arg name="dashboard_config_file" value="$(find-pkg-share barista_rmf_gazebo)/dashboard_config/$(var map_name)/dashboard_config.json"/>
  </include>

  <!-- Barista fleet adapter, and robot state aggregator. These should comunicate with the barista fleet server of FF -->
  <group>
    <let name="fleet_name" value="turtlebot3"/>
    <include file="$(find-pkg-share barista_rmf_gazebo)/adapter_config/turtlebot3_adapter.launch.xml">
      <arg name="fleet_name" value="$(var fleet_name)"/>
      <arg name="use_sim_time" value="$(var use_sim_time)"/>
      <arg name="nav_graph_file" value="$(find-pkg-share barista_rmf_gazebo)/maps/$(var map_name)/nav_graphs/0.yaml" />

    </include>
    <include file="$(find-pkg-share rmf_fleet_adapter)/robot_state_aggregator.launch.xml">
      <arg name="robot_prefix" value="$(var fleet_name)"/>
      <arg name="fleet_name" value="$(var fleet_name)"/>
      <arg name="use_sim_time" value="$(var use_sim_time)"/>
      <arg name="failover_mode" value="$(var failover_mode)"/>
    </include>
  </group>

</launch>
```

my  **turtlebot3_adapter.launch.xml**

```
<?xml version='1.0' ?>

<launch>

  <arg name="fleet_name" default="turtlebot3" description="Name of this fleet of barista robots"/>
  <arg name="use_sim_time" default="false" description="Use the /clock topic for time to sync with simulation"/>
  <arg name="nav_graph_file" description="Nav graph required by fleet adapter"/>
  <arg name="finishing_request" default="nothing"
       description="What the robot should do once it finishes its tasks: [charge, park, nothing]"/>
  <group>
    <include file="$(find-pkg-share rmf_fleet_adapter)/fleet_adapter.launch.xml">
      <!-- The name and control type of the fleet -->
      <arg name="fleet_name" value="$(var fleet_name)"/>
      <arg name="control_type" value="full_control"/>
      <!-- The graph that this fleet should use for navigation -->
      <arg name="nav_graph_file" value="$(var nav_graph_file)" />
      <!-- The nominal linear and angular velocity of this fleet's vehicles -->
      <arg name="linear_velocity" value="0.2"/>
      <arg name="angular_velocity" value="0.3"/>
      <!-- The nominal linear and angular acceleration of this fleet's vehicles -->
      <arg name="linear_acceleration" value="0.35"/>
      <arg name="angular_acceleration" value="0.5"/>
      <!-- The radius of the circular footprint of this fleet's vehicles -->
      <arg name="footprint_radius" value="0.2"/>
      <!-- Other robots are not allowed within this radius --> 
      <arg name="vicinity_radius" value="0.22"/>
      <!-- Whether to use sim time -->
      <arg name="use_sim_time" value="$(var use_sim_time)"/>
      <!-- How long it can be delayed before we give up and start over -->
      <arg name="delay_threshold" value="15.0"/>
      <!-- Don't make the barista wait long to retry -->
      <arg name="retry_wait" value="10.0"/>
      <!-- Give everything time to discover -->
      <arg name="discovery_timeout" value="60.0"/>
      <!-- Can the robot drive backwards -->
      <arg name="reversible" value="false"/>
      <!-- Whether it can perform deliveries -->
      <arg name="perform_deliveries" value="true"/>
      <!-- Whether it can perform loop -->
      <arg name="perform_loop" value="true"/>
      <!-- Whether it can perform cleaning -->
      <arg name="perform_cleaning" value="false"/>
      <!-- What the robot should do once it finishes its tasks -->
      <arg name="finishing_request" value="$(var finishing_request)"/>
      <!-- TODO Update these values with actual specs -->
      <!-- Battery parameters -->
      <arg name="battery_voltage" value="12.0"/>
      <arg name="battery_capacity" value="24.0"/>
      <arg name="battery_charging_current" value="5.0"/>
      <!-- Physical parameters -->
      <arg name="mass" value="20.0"/>
      <arg name="inertia" value="10.0"/>
      <arg name="friction_coefficient" value="0.22"/>
      <!-- Power systems -->
      <arg name="ambient_power_drain" value="20.0"/>
      <arg name="tool_power_drain" value="0.0"/>
      <!-- Whether to consider battery drain for task planning -->
      <arg name="drain_battery" value="true"/>
      <!-- Battery level at which the robot ceases to operate -->
      <arg name="recharge_threshold" value="0.3"/>
      <!-- Battery level at which we consider the robot battery fully charged -->
      <arg name="recharge_soc" value="1.0"/
    </include>
  </group>
</launch>
```

my **ff.building.yaml**

```
crowd_sim:
  agent_groups:
    - {agents_name: [], agents_number: 0, group_id: 0, profile_selector: external_agent, state_selector: external_static, x: 0, y: 0}
  agent_profiles:
    - {ORCA_tau: 1, ORCA_tauObst: 0.4, class: 1, max_accel: 0, max_angle_vel: 0, max_neighbors: 10, max_speed: 0, name: external_agent, neighbor_dist: 5, obstacle_set: 1, pref_speed: 0, r: 0.25}
  enable: 0
  goal_sets: []
  model_types: []
  obstacle_set: {class: 1, file_name: L1_navmesh.nav, type: nav_mesh}
  states:
    - {final: 1, goal_set: -1, name: external_static, navmesh_file_name: ""}
  transitions: []
  update_time_step: 0.1
graphs:
  {}
levels:
  L1:
    drawing:
      filename: turtle3_map.png
    elevation: 0
    flattened_x_offset: 0
    flattened_y_offset: 0
    lanes:
      - [16, 17, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""]}]
      - [17, 18, {bidirectional: [4, false], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""]}]
    layers:
      {}
    measurements:
      - [0, 8, {distance: [3, 5.4]}]
    vertices:
      - [141.728, 183.682, 0, ""]
      - [163.605, 144.534, 0, ""]
      - [172.816, 143.383, 0, ""]
      - [178.573, 134.556, 0, ""]
      - [223.094, 133.404, 0, ""]
      - [227.7, 144.534, 0, ""]
      - [237.679, 144.918, 0, ""]
      - [253.415, 173.32, 0, ""]
      - [248.042, 184.834, 0, ""]
      - [253.031, 194.813, 0, ""]
      - [236.528, 223.214, 0, ""]
      - [228.468, 224.366, 0, ""]
      - [222.327, 233.961, 0, ""]
      - [178.957, 235.88, 0, ""]
      - [172.432, 223.982, 0, ""]
      - [163.221, 223.214, 0, ""]
      - [165.524, 182.531, 0, turtlebot3, {spawn_robot_name: [1, "ros2_tb3_0"], spawn_robot_type: [1, turtlebot3_burger]}]
      - [165.908, 212.084, 0, ""]
      - [231.538, 213.619, 0, ""]
    walls:
      - [0, 1, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [1, 2, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [2, 3, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [3, 4, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [4, 5, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [5, 6, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [6, 7, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [7, 8, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [8, 9, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [9, 10, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [10, 11, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [11, 12, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [12, 13, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [13, 14, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [14, 15, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [15, 0, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
lifts: {}
name: ff
```

my **0.yaml**

```
building_name: ff
levels:
  L1:
    lanes:
    - - 0
      - 1
      - {is_bidirectional: false}
    - - 1
      - 2
      - {is_bidirectional: false}
    vertices:
    - - 8.406956092930983
      - -9.270740814617731
      - {name: turtlebot3, spawn_robot_name: ros2_tb3_0, spawn_robot_type: turtlebot3_burger}
    - - 8.426459434680128
      - -10.77173628001483
      - {name: ''}
    - - 11.759804015399906
      - -10.84969885705894
      - {name: ''}

```
**I was visualizing the robot in some where else not in the map...**

qdn@AVDHESH:~/rmf$ ros2 launch  barista_rmf_gazebo start_rmf_turtlebotworld.launch.xml 
[INFO] [launch]: All log files can be found below /home/qdn/.ros/log/2024-10-16-16-44-43-689497-AVDHESH-74556
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rmf_traffic_schedule-1]: process started with pid [74559]
[INFO] [rmf_traffic_schedule_monitor-2]: process started with pid [74561]
[INFO] [rmf_traffic_blockade-3]: process started with pid [74563]
[INFO] [building_map_server-4]: process started with pid [74565]
[INFO] [schedule_visualizer-5]: process started with pid [74568]
[INFO] [rmf_visualization_fleet_states-6]: process started with pid [74570]
[INFO] [rmf_visualization_building_systems-7]: process started with pid [74572]
[INFO] [rviz2-8]: process started with pid [74574]
[INFO] [door_supervisor-9]: process started with pid [74576]
[INFO] [lift_supervisor-10]: process started with pid [74578]
[INFO] [rmf_task_dispatcher-11]: process started with pid [74594]
[INFO] [simple_api_server-12]: process started with pid [74629]
[INFO] [full_control-13]: process started with pid [74646]
[INFO] [robot_state_aggregator-14]: process started with pid [74649]
[rmf_task_dispatcher-11] ~Initializing Dispatcher Node~
[rmf_traffic_schedule-1] [INFO] [1729077284.241190628] [rmf_traffic_schedule_primary]: Successfully loaded logfile .rmf_schedule_node.yaml 
[rmf_traffic_schedule-1] [INFO] [1729077284.242380137] [rmf_traffic_schedule_primary]: Set up heartbeat on /rmf_traffic/heartbeat with liveliness lease duration of 1000 ms and deadline of 1000 ms
[rmf_traffic_schedule-1] [INFO] [1729077284.243419238] [rmf_traffic_schedule_primary]: Beginning traffic schedule node
[rmf_traffic_schedule_monitor-2] [INFO] [1729077284.248394552] [rmf_traffic_schedule_backup]: Set up heartbeat listener on /rmf_traffic/heartbeat with liveliness lease duration of 1000 ms
[rmf_traffic_blockade-3] [INFO] [1729077284.262811915] [rmf_traffic_blockade_node]: Beginning traffic blockade node
[rmf_task_dispatcher-11] [INFO] [1729077284.272178636] [rmf_dispatcher_node]:  Declared Time Window Param as: 2.000000 secs
[rmf_task_dispatcher-11] [INFO] [1729077284.272249019] [rmf_dispatcher_node]:  Declared Terminated Tasks Max Size Param as: 100
[rmf_task_dispatcher-11] [INFO] [1729077284.272261491] [rmf_dispatcher_node]:  Declared publish_active_tasks_period as: 0.000000 secs
[rmf_task_dispatcher-11] [INFO] [1729077284.273650003] [rmf_dispatcher_node]: Starting task dispatcher node
[rmf_traffic_schedule-1] [INFO] [1729077284.344358211] [rmf_traffic_schedule_primary]: Registered new query [1]
[full_control-13] [INFO] [1729077284.392654671] [turtlebot3_fleet_adapter]: Parameter [discovery_timeout] set to: 60.000000
[schedule_visualizer-5] [INFO] [1729077284.395718955] [rmf_visualization_schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [0]
[rmf_traffic_schedule-1] [INFO] [1729077284.399829162] [rmf_traffic_schedule_primary]: A new mirror is tracking query ID [1]
[schedule_visualizer-5] [INFO] [1729077284.408929504] [rmf_visualization_schedule_data_node]: rmf_visualization_schedule_data_node started...
[schedule_visualizer-5] [INFO] [1729077284.409348477] [rmf_visualization_schedule_data_node]: Websocket server started on port: 8006
[full_control-13] [INFO] [1729077284.434553151] [turtlebot3_fleet_adapter]: Parameter [linear_velocity] set to: 0.200000
[full_control-13] [INFO] [1729077284.434644708] [turtlebot3_fleet_adapter]: Parameter [angular_velocity] set to: 0.300000
[full_control-13] [INFO] [1729077284.434711234] [turtlebot3_fleet_adapter]: Parameter [linear_acceleration] set to: 0.350000
[full_control-13] [INFO] [1729077284.434760165] [turtlebot3_fleet_adapter]: Parameter [angular_acceleration] set to: 0.500000
[full_control-13] [INFO] [1729077284.434800700] [turtlebot3_fleet_adapter]: Parameter [footprint_radius] set to: 0.200000
[full_control-13] [INFO] [1729077284.434879883] [turtlebot3_fleet_adapter]: Parameter [vicinity_radius] set to: 0.220000
[full_control-13] [INFO] [1729077284.434954421] [turtlebot3_fleet_adapter]: Parameter [reversible] set to: 0
[full_control-13]  ===== We have an irreversible robot
[full_control-13] The fleet [turtlebot3] has the following named waypoints:
[full_control-13]  -- turtlebot3
[full_control-13] [INFO] [1729077284.443823341] [turtlebot3_fleet_adapter]: Parameter [battery_voltage] set to: 12.000000
[rmf_traffic_schedule_monitor-2] [INFO] [1729077284.444348125] [rmf_traffic_schedule_backup]: Liveliness changed event:
[rmf_traffic_schedule_monitor-2] [INFO] [1729077284.444386634] [rmf_traffic_schedule_backup]:   alive_count: 1
[rmf_traffic_schedule_monitor-2] [INFO] [1729077284.444398621] [rmf_traffic_schedule_backup]:   not_alive_count: 0
[rmf_traffic_schedule_monitor-2] [INFO] [1729077284.444409053] [rmf_traffic_schedule_backup]:   alive_count_change: 1
[rmf_traffic_schedule_monitor-2] [INFO] [1729077284.444417798] [rmf_traffic_schedule_backup]:   not_alive_count_change: 0
[full_control-13] [INFO] [1729077284.444790800] [turtlebot3_fleet_adapter]: Parameter [battery_capacity] set to: 24.000000
[full_control-13] [INFO] [1729077284.444936633] [turtlebot3_fleet_adapter]: Parameter [battery_charging_current] set to: 5.000000
[full_control-13] [INFO] [1729077284.445063452] [turtlebot3_fleet_adapter]: Parameter [mass] set to: 20.000000
[full_control-13] [INFO] [1729077284.445450947] [turtlebot3_fleet_adapter]: Parameter [inertia] set to: 10.000000
[full_control-13] [INFO] [1729077284.446066597] [turtlebot3_fleet_adapter]: Parameter [friction_coefficient] set to: 0.220000
[full_control-13] [INFO] [1729077284.446234636] [turtlebot3_fleet_adapter]: Parameter [ambient_power_drain] set to: 20.000000
[full_control-13] [INFO] [1729077284.446357234] [turtlebot3_fleet_adapter]: Parameter [tool_power_drain] set to: 0.000000
[full_control-13] [INFO] [1729077284.446487312] [turtlebot3_fleet_adapter]: Parameter [drain_battery] set to: 1
[full_control-13] [INFO] [1729077284.446647621] [turtlebot3_fleet_adapter]: Parameter [recharge_threshold] set to: 0.300000
[full_control-13] [INFO] [1729077284.446779962] [turtlebot3_fleet_adapter]: Parameter [recharge_soc] set to: 1.000000
[full_control-13] [INFO] [1729077284.446927580] [turtlebot3_fleet_adapter]: Fleet is not configured to perform any finishing request
[full_control-13] [INFO] [1729077284.447549213] [turtlebot3_fleet_adapter]: Parameter [delay_threshold] set to: 15.000000
[schedule_visualizer-5] [INFO] [1729077284.449817219] [rmf_visualization_schedule_data_node]: Mirror handling new sync of 1 queries from schedule node version [0]
[rmf_traffic_schedule-1] [INFO] [1729077284.452691540] [rmf_traffic_schedule_primary]: A new mirror is tracking query ID [1]
[full_control-13] [INFO] [1729077284.453997171] [turtlebot3_fleet_adapter]: Starting Fleet Adapter
[rmf_traffic_schedule_monitor-2] [INFO] [1729077284.454123818] [rmf_traffic_schedule_backup]: Handling new sync of 1 queries from primary node
[rmf_traffic_schedule_monitor-2] [INFO] [1729077284.454334739] [rmf_traffic_schedule_backup]: Got mirror for monitor node
[schedule_visualizer-5] [INFO] [1729077284.454248025] [rmf_visualization_schedule_data_node]: Mirror handling new sync of 1 queries from schedule node version [0]
[full_control-13] [INFO] [1729077284.457672034] [turtlebot3_fleet_adapter]: Mirror handling new sync of 1 queries from schedule node version [0]
[full_control-13] [INFO] [1729077284.461294365] [turtlebot3_fleet_adapter]: Mirror handling new sync of 1 queries from schedule node version [0]
**[full_control-13] [ERROR] [1729077284.529170205] [turtlebot3_fleet_adapter]: Unable to compute a StartSet for robot [ros2_tb3_0] using level_name [L1] and location [-1.894945, -0.420001, 0.000001] specified in its RobotState message. This can happen if the level_name in the RobotState message does not match any of the map names in the navigation graph supplied or if the location reported in the RobotState message is far way from the navigation graph. This robot will not be added to the fleet [turtlebot3]. The following hint may help with debugging: The closest waypoint on the navigation graph [turtlebot3] is a distance of [13.581781m] from the robot.**
[rmf_traffic_schedule_monitor-2] [INFO] [1729077284.569121304] [rmf_traffic_schedule_backup]: Mirror handling new sync of 1 queries from schedule node version [0]
[rmf_visualization_fleet_states-6] [INFO] [1729077284.712065548] [fleet_state_visualizer]: hello i am fleet state visualizer
[rviz2-8] [INFO] [1729077284.739578345] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-8] [INFO] [1729077284.739697874] [rviz2]: OpenGl version: 3.1 (GLSL 1.4)
[rmf_visualization_building_systems-7] [INFO] [1729077284.766325346] [building_systems_visualizer]: Building systems visualizer started...
[rviz2-8] [INFO] [1729077284.806173382] [rviz2]: Stereo is NOT SUPPORTED
[simple_api_server-12] Set Server IP to: 0.0.0.0
[simple_api_server-12] Set Server port to: 0.0.0.0:8083
[simple_api_server-12] Starting RMF_Demos API Server: 0.0.0.0:8083
[simple_api_server-12]  * Serving Flask app 'rmf_demos_panel.simple_api_server'
[simple_api_server-12]  * Debug mode: off
[schedule_visualizer-5] [INFO] [1729077284.959240992] [rmf_visualization_schedule_marker_publisher]: Rviz parameters updated
[building_map_server-4] [INFO] [1729077285.019655295] [building_map_server]: loading map path: /home/qdn/rmf/install/barista_rmf_gazebo/share/barista_rmf_gazebo/rmf_config/ff.building.yaml
[building_map_server-4] [INFO] [1729077285.037594495] [building_map_server]: opening: /home/qdn/rmf/install/barista_rmf_gazebo/share/barista_rmf_gazebo/rmf_config/turtle3_map.png
[building_map_server-4] [INFO] [1729077285.038752985] [building_map_server]: read 1640 byte image
[building_map_server-4] [INFO] [1729077285.042839806] [building_map_server]: publishing map...
[building_map_server-4] [INFO] [1729077285.044248775] [building_map_server]: ready to serve map: "ff"  Ctrl+C to exit...
[schedule_visualizer-5] [INFO] [1729077285.271946394] [rmf_visualization_schedule_marker_publisher]: Received map "ff" containing 1 level(s)
[schedule_visualizer-5] [INFO] [1729077285.272062111] [rmf_visualization_schedule_marker_publisher]: Level cache updated
[schedule_visualizer-5] [INFO] [1729077285.272191201] [rmf_visualization_schedule_marker_publisher]: Loading floorplan Image: turtle3_map png
[rviz2-8] [INFO] [1729077285.325450998] [rviz2]: Trying to create a map of size 384 x 384 using 1 swatches
[rviz2-8] [ERROR] [1729077285.332152829] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : 
[rviz2-8] active samplers with a different type refer to the same texture image unit
[full_control-13] [INFO] [1729077289.419466605] [turtlebot3_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [0]
[full_control-13] [INFO] [1729077294.427398959] [turtlebot3_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [5]
[schedule_visualizer-5] [INFO] [1729077294.427709155] [rmf_visualization_schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [5]
[rmf_traffic_schedule_monitor-2] [INFO] [1729077294.427955717] [rmf_traffic_schedule_backup]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [5]
[full_control-13] [INFO] [1729077299.425719421] [turtlebot3_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [5]
[schedule_visualizer-5] [INFO] [1729077299.425732790] [rmf_visualization_schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [5]
[rmf_traffic_schedule_monitor-2] [INFO] [1729077299.426820401] [rmf_traffic_schedule_backup]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since version [5]
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[rviz2-8] [INFO] [1729077300.944124936] [rclcpp]: signal_handler(signal_value=2)
[full_control-13] [INFO] [1729077300.944130978] [rclcpp]: signal_handler(signal_value=2)
[rmf_task_dispatcher-11] [INFO] [1729077300.944140951] [rclcpp]: signal_handler(signal_value=2)
[robot_state_aggregator-14] [INFO] [1729077300.944110078] [rclcpp]: signal_handler(signal_value=2)
[door_supervisor-9] [INFO] [1729077300.944150124] [rclcpp]: signal_handler(signal_value=2)
[lift_supervisor-10] [INFO] [1729077300.944193789] [rclcpp]: signal_handler(signal_value=2)
[rmf_traffic_schedule-1] [INFO] [1729077300.944288668] [rclcpp]: signal_handler(signal_value=2)
[rmf_visualization_fleet_states-6] /opt/ros/galactic/lib/python3.8/site-packages/rclpy/node.py:440: UserWarning: when declaring parmater named 'display_names', declaring a parameter only providing its name is deprecated. You have to either:
[rmf_visualization_fleet_states-6] 	- Pass a name and a default value different to "PARAMETER NOT SET" (and optionally a descriptor).
[rmf_visualization_fleet_states-6] 	- Pass a name and a parameter type.
[rmf_visualization_fleet_states-6] 	- Pass a name and a descriptor with `dynamic_typing=True
[rmf_visualization_fleet_states-6]   warnings.warn(
[building_map_server-4] /opt/ros/galactic/lib/python3.8/site-packages/rclpy/qos.py:307: UserWarning: HistoryPolicy.RMW_QOS_POLICY_HISTORY_KEEP_LAST is deprecated. Use HistoryPolicy.KEEP_LAST instead.
[building_map_server-4]   warnings.warn(
[building_map_server-4] /opt/ros/galactic/lib/python3.8/site-packages/rclpy/qos.py:307: UserWarning: ReliabilityPolicy.RMW_QOS_POLICY_RELIABILITY_RELIABLE is deprecated. Use ReliabilityPolicy.RELIABLE instead.

Please anyone please help me how to solve this error .
